site_name: UnrealCV
theme: readthedocs
repo_url: https://github.com/unrealcv/unrealcv/
edit_uri: edit/doc/docs/
strict: true
markdown_extensions:
    - markdown.extensions.admonition
    - markdown.extensions.def_list
pages:
    - "Welcome": index.md
    - "Getting started": getting-started.md
    - "Game Mode":
        - "Generate images": "ipynb/generate-images.md"
        - "Integrate with external programs": "game/faster-rcnn.md"
        - "Configuration": "game/configuration.md"
    - "Plugin Mode":
        - "Plugin installation": plugin/install.md
        - "Modify a virtual world": plugin/usage.md
        - "Package a game": "plugin/package-game.md"
        - "Development setup": plugin/dev.md
        - "Add new UnrealCV commands": plugin/add-command.md
    - "Reference":
        - "Architecture": reference/arch.md
        - "Command List": reference/command.md
        - "UE4 Resources": reference/ue4_resource.md
        - "Model zoo": reference/model-zoo.md
        - "API docs": reference/api.md
        - "Issues": reference/issues.md
    - "Contact": contact.md
extra:
    version: v0.3.0
    codebase: https://github.com/unrealcv/unrealcv
